import Foundation

public enum TimelineEditError: Error, Equatable, Sendable {
    case invalidAssetDuration(AssetID)
    case invalidTimeline
    case revisionOverflow
    case duplicateClip(ClipID)
    case clipNotFound(ClipID)
    case trackNotFound(TrackID)
    case trackLocked(TrackID)
    case invalidSourceRange(ClipID)
    case invalidSplit(ClipID)
    case invalidMoveIndex(Int)
    case historyUnavailable
    case historyMismatch
}

extension TimelineEditError: LocalizedError {
    public var errorDescription: String? {
        switch self {
        case .invalidAssetDuration:
            "The source has no usable duration."
        case .invalidTimeline:
            "The timeline contains invalid or overflowing clip data."
        case .revisionOverflow:
            "The timeline revision can no longer be advanced."
        case .duplicateClip:
            "The edit would create a duplicate timeline clip."
        case .clipNotFound:
            "The selected timeline clip no longer exists."
        case .trackNotFound:
            "The selected timeline track no longer exists."
        case .trackLocked:
            "Unlock this timeline track before editing it."
        case .invalidSourceRange:
            "The requested trim is outside the immutable source."
        case .invalidSplit:
            "Choose a split point inside the clip."
        case .invalidMoveIndex:
            "The clip cannot be moved to that position."
        case .historyUnavailable:
            "There is no timeline edit to restore."
        case .historyMismatch:
            "The saved edit history does not belong to this timeline."
        }
    }
}

/// Commands are value types so the same validated operation can be persisted,
/// replayed, tested, and eventually generated by automatic suggestions.
public enum TimelineCommand: Hashable, Codable, Sendable {
    case addClip(
        trackID: TrackID,
        trackKind: TrackKind,
        trackOrder: Int,
        clip: TimelineClip
    )
    case trim(clipID: ClipID, sourceRange: StudioTimeRange)
    case split(clipID: ClipID, sourceTime: StudioTime, trailingClipID: ClipID)
    case move(clipID: ClipID, toIndex: Int)
    case delete(clipID: ClipID)
    case setEnabled(clipID: ClipID, isEnabled: Bool)
}

public struct TimelineHistoryEntry: Hashable, Codable, Sendable {
    public var command: TimelineCommand
    public var before: TimelineDocument
    public var after: TimelineDocument

    public init(command: TimelineCommand, before: TimelineDocument, after: TimelineDocument) {
        self.command = command
        self.before = before
        self.after = after
    }
}

/// Persisted separately from `timeline.json`: the timeline remains the canonical
/// edit graph while this bounded stack provides relaunch-safe undo and redo.
public struct TimelineEditHistory: Hashable, Codable, Sendable {
    public static let currentSchemaVersion = 1
    public static let maximumEntryCount = 50

    public var schemaVersion: Int
    public var timelineID: TimelineID
    public var projectID: ProjectID
    public var undoStack: [TimelineHistoryEntry]
    public var redoStack: [TimelineHistoryEntry]

    public init(
        timelineID: TimelineID,
        projectID: ProjectID,
        undoStack: [TimelineHistoryEntry] = [],
        redoStack: [TimelineHistoryEntry] = []
    ) {
        schemaVersion = Self.currentSchemaVersion
        self.timelineID = timelineID
        self.projectID = projectID
        self.undoStack = undoStack
        self.redoStack = redoStack
    }

    public init(timeline: TimelineDocument) {
        self.init(timelineID: timeline.id, projectID: timeline.projectID)
    }

    public var canUndo: Bool { !undoStack.isEmpty }
    public var canRedo: Bool { !redoStack.isEmpty }

    public mutating func record(
        command: TimelineCommand,
        before: TimelineDocument,
        after: TimelineDocument,
        maximumEntries: Int = Self.maximumEntryCount
    ) throws {
        guard maximumEntries > 0,
              timelineID == before.id,
              timelineID == after.id,
              projectID == before.projectID,
              projectID == after.projectID
        else {
            throw TimelineEditError.historyMismatch
        }

        undoStack.append(TimelineHistoryEntry(command: command, before: before, after: after))
        if undoStack.count > maximumEntries {
            undoStack.removeFirst(undoStack.count - maximumEntries)
        }
        redoStack.removeAll(keepingCapacity: true)
    }
}

public struct TimelineEditState: Hashable, Sendable {
    public var timeline: TimelineDocument
    public var history: TimelineEditHistory

    public init(timeline: TimelineDocument, history: TimelineEditHistory) {
        self.timeline = timeline
        self.history = history
    }
}

public struct TimelineAppendResult: Hashable, Sendable {
    public var timeline: TimelineDocument
    public var clip: TimelineClip
    public var command: TimelineCommand

    public init(timeline: TimelineDocument, clip: TimelineClip, command: TimelineCommand) {
        self.timeline = timeline
        self.clip = clip
        self.command = command
    }
}

/// Deterministic, non-destructive timeline reducer shared by the app, project
/// store, tests, and future suggestion handlers.
public struct TimelineEditor: Sendable {
    public init() {}

    public func appending(
        asset: SourceAsset,
        to timeline: TimelineDocument,
        assetDurations: [AssetID: StudioTime] = [:]
    ) throws -> TimelineAppendResult {
        guard asset.duration > .zero else {
            throw TimelineEditError.invalidAssetDuration(asset.id)
        }

        let trackKind = Self.trackKind(for: asset.kind)
        let track: TimelineTrack
        if let existing = timeline.tracks.first(where: { $0.kind == trackKind }) {
            track = existing
        } else {
            let highestOrder = timeline.tracks.map(\.order).max() ?? -1
            guard highestOrder < Int.max else { throw TimelineEditError.invalidTimeline }
            track = TimelineTrack(kind: trackKind, order: highestOrder + 1)
        }

        let clip = TimelineClip(
            assetID: asset.id,
            sourceRange: StudioTimeRange(start: .zero, duration: asset.duration),
            timelineStart: .zero
        )
        let command = TimelineCommand.addClip(
            trackID: track.id,
            trackKind: track.kind,
            trackOrder: track.order,
            clip: clip
        )
        var allAssetDurations = assetDurations
        allAssetDurations[asset.id] = asset.duration
        let edited = try applying(command, to: timeline, assetDurations: allAssetDurations)
        guard let appended = edited.tracks
            .flatMap(\.clips)
            .first(where: { $0.id == clip.id })
        else {
            throw TimelineEditError.invalidTimeline
        }
        return TimelineAppendResult(timeline: edited, clip: appended, command: command)
    }

    public func performing(
        _ command: TimelineCommand,
        on timeline: TimelineDocument,
        history: TimelineEditHistory,
        assetDurations: [AssetID: StudioTime]
    ) throws -> TimelineEditState {
        let edited = try applying(command, to: timeline, assetDurations: assetDurations)
        var history = history
        try history.record(command: command, before: timeline, after: edited)
        return TimelineEditState(timeline: edited, history: history)
    }

    public func undoing(
        _ timeline: TimelineDocument,
        history: TimelineEditHistory
    ) throws -> TimelineEditState {
        try Self.validate(history: history, for: timeline)
        guard let entry = history.undoStack.last else {
            throw TimelineEditError.historyUnavailable
        }

        var history = history
        history.undoStack.removeLast()
        history.redoStack.append(entry)
        var restored = entry.before
        restored.revision = try Self.nextRevision(after: timeline.revision)
        return TimelineEditState(timeline: restored, history: history)
    }

    public func redoing(
        _ timeline: TimelineDocument,
        history: TimelineEditHistory
    ) throws -> TimelineEditState {
        try Self.validate(history: history, for: timeline)
        guard let entry = history.redoStack.last else {
            throw TimelineEditError.historyUnavailable
        }

        var history = history
        history.redoStack.removeLast()
        history.undoStack.append(entry)
        var restored = entry.after
        restored.revision = try Self.nextRevision(after: timeline.revision)
        return TimelineEditState(timeline: restored, history: history)
    }

    public func applying(
        _ command: TimelineCommand,
        to timeline: TimelineDocument,
        assetDurations: [AssetID: StudioTime] = [:]
    ) throws -> TimelineDocument {
        try Self.validate(timeline: timeline, assetDurations: assetDurations)
        var timeline = timeline

        switch command {
        case let .addClip(trackID, trackKind, trackOrder, clip):
            guard !timeline.tracks.flatMap(\.clips).contains(where: { $0.id == clip.id }) else {
                throw TimelineEditError.duplicateClip(clip.id)
            }
            try Self.validate(clip: clip, assetDurations: assetDurations)

            let trackIndex: Int
            if let existing = timeline.tracks.firstIndex(where: { $0.id == trackID }) {
                guard timeline.tracks[existing].kind == trackKind,
                      timeline.tracks[existing].order == trackOrder
                else {
                    throw TimelineEditError.invalidTimeline
                }
                trackIndex = existing
            } else {
                guard trackOrder >= 0,
                      !timeline.tracks.contains(where: { $0.kind == trackKind || $0.order == trackOrder })
                else {
                    throw TimelineEditError.invalidTimeline
                }
                timeline.tracks.append(TimelineTrack(id: trackID, kind: trackKind, order: trackOrder))
                trackIndex = timeline.tracks.count - 1
            }
            try Self.requireUnlocked(timeline.tracks[trackIndex])
            timeline.tracks[trackIndex].clips.append(clip)
            try Self.ripple(trackAt: trackIndex, in: &timeline, assetDurations: assetDurations)

        case let .trim(clipID, sourceRange):
            let location = try Self.location(of: clipID, in: timeline)
            try Self.requireUnlocked(timeline.tracks[location.track])
            timeline.tracks[location.track].clips[location.clip].sourceRange = sourceRange
            try Self.validate(
                clip: timeline.tracks[location.track].clips[location.clip],
                assetDurations: assetDurations
            )
            try Self.ripple(trackAt: location.track, in: &timeline, assetDurations: assetDurations)

        case let .split(clipID, sourceTime, trailingClipID):
            guard !timeline.tracks.flatMap(\.clips).contains(where: { $0.id == trailingClipID }) else {
                throw TimelineEditError.duplicateClip(trailingClipID)
            }
            let location = try Self.location(of: clipID, in: timeline)
            try Self.requireUnlocked(timeline.tracks[location.track])
            var leading = timeline.tracks[location.track].clips[location.clip]
            let sourceEnd = try Self.safeEnd(of: leading.sourceRange)
            guard sourceTime > leading.sourceRange.start, sourceTime < sourceEnd else {
                throw TimelineEditError.invalidSplit(clipID)
            }

            var trailing = leading
            trailing.id = trailingClipID
            leading.sourceRange = StudioTimeRange(
                start: leading.sourceRange.start,
                duration: sourceTime - leading.sourceRange.start
            )
            trailing.sourceRange = StudioTimeRange(
                start: sourceTime,
                duration: sourceEnd - sourceTime
            )
            timeline.tracks[location.track].clips[location.clip] = leading
            timeline.tracks[location.track].clips.insert(trailing, at: location.clip + 1)
            try Self.ripple(trackAt: location.track, in: &timeline, assetDurations: assetDurations)

        case let .move(clipID, toIndex):
            let location = try Self.location(of: clipID, in: timeline)
            try Self.requireUnlocked(timeline.tracks[location.track])
            let clipCount = timeline.tracks[location.track].clips.count
            guard toIndex >= 0, toIndex < clipCount else {
                throw TimelineEditError.invalidMoveIndex(toIndex)
            }
            let clip = timeline.tracks[location.track].clips.remove(at: location.clip)
            timeline.tracks[location.track].clips.insert(clip, at: toIndex)
            try Self.ripple(trackAt: location.track, in: &timeline, assetDurations: assetDurations)

        case let .delete(clipID):
            let location = try Self.location(of: clipID, in: timeline)
            try Self.requireUnlocked(timeline.tracks[location.track])
            timeline.tracks[location.track].clips.remove(at: location.clip)
            try Self.ripple(trackAt: location.track, in: &timeline, assetDurations: assetDurations)

        case let .setEnabled(clipID, isEnabled):
            let location = try Self.location(of: clipID, in: timeline)
            try Self.requireUnlocked(timeline.tracks[location.track])
            timeline.tracks[location.track].clips[location.clip].isEnabled = isEnabled
        }

        timeline.revision = try Self.nextRevision(after: timeline.revision)
        return timeline
    }

    private static func validate(
        timeline: TimelineDocument,
        assetDurations: [AssetID: StudioTime]
    ) throws {
        var trackIDs = Set<TrackID>()
        var trackOrders = Set<Int>()
        var clipIDs = Set<ClipID>()
        for track in timeline.tracks {
            guard track.order >= 0,
                  trackIDs.insert(track.id).inserted,
                  trackOrders.insert(track.order).inserted
            else {
                throw TimelineEditError.invalidTimeline
            }
            for clip in track.clips {
                guard clipIDs.insert(clip.id).inserted, clip.timelineStart >= .zero else {
                    throw TimelineEditError.invalidTimeline
                }
                try validate(clip: clip, assetDurations: assetDurations)
            }
        }
    }

    private static func validate(
        clip: TimelineClip,
        assetDurations: [AssetID: StudioTime]
    ) throws {
        guard clip.sourceRange.start >= .zero,
              clip.sourceRange.duration > .zero,
              clip.playbackRate.isFinite,
              clip.playbackRate > 0,
              clip.timelineDuration > .zero
        else {
            throw TimelineEditError.invalidSourceRange(clip.id)
        }
        let sourceEnd = try safeEnd(of: clip.sourceRange)
        if let assetDuration = assetDurations[clip.assetID], sourceEnd > assetDuration {
            throw TimelineEditError.invalidSourceRange(clip.id)
        }
    }

    private static func ripple(
        trackAt trackIndex: Int,
        in timeline: inout TimelineDocument,
        assetDurations: [AssetID: StudioTime]
    ) throws {
        var start = StudioTime.zero
        for clipIndex in timeline.tracks[trackIndex].clips.indices {
            var clip = timeline.tracks[trackIndex].clips[clipIndex]
            try validate(clip: clip, assetDurations: assetDurations)
            clip.timelineStart = start
            timeline.tracks[trackIndex].clips[clipIndex] = clip
            let (next, overflow) = start.microseconds.addingReportingOverflow(clip.timelineDuration.microseconds)
            guard !overflow else { throw TimelineEditError.invalidTimeline }
            start = StudioTime(microseconds: next)
        }
    }

    private static func location(
        of clipID: ClipID,
        in timeline: TimelineDocument
    ) throws -> (track: Int, clip: Int) {
        for trackIndex in timeline.tracks.indices {
            if let clipIndex = timeline.tracks[trackIndex].clips.firstIndex(where: { $0.id == clipID }) {
                return (trackIndex, clipIndex)
            }
        }
        throw TimelineEditError.clipNotFound(clipID)
    }

    private static func requireUnlocked(_ track: TimelineTrack) throws {
        guard !track.isLocked else { throw TimelineEditError.trackLocked(track.id) }
    }

    private static func safeEnd(of range: StudioTimeRange) throws -> StudioTime {
        let (microseconds, overflow) = range.start.microseconds
            .addingReportingOverflow(range.duration.microseconds)
        guard !overflow else { throw TimelineEditError.invalidTimeline }
        return StudioTime(microseconds: microseconds)
    }

    private static func nextRevision(after revision: Int) throws -> Int {
        guard revision < Int.max else { throw TimelineEditError.revisionOverflow }
        return revision + 1
    }

    private static func validate(
        history: TimelineEditHistory,
        for timeline: TimelineDocument
    ) throws {
        guard history.schemaVersion <= TimelineEditHistory.currentSchemaVersion,
              history.timelineID == timeline.id,
              history.projectID == timeline.projectID
        else {
            throw TimelineEditError.historyMismatch
        }
    }

    private static func trackKind(for mediaKind: MediaKind) -> TrackKind {
        switch mediaKind {
        case .screenVideo: .screen
        case .cameraVideo: .camera
        case .appAudio: .appAudio
        case .microphoneAudio: .microphone
        case .music: .music
        case .image, .overlay: .overlay
        }
    }
}
